// gui/vue/src/components/helpers/LogicBox.vue
<template>
  <div v-if="isLogicBox" class="position-relative shadow border p-3 mt-3"
       v-bind:class="[{'is-invalid': errors.length > 0}, ...styleClass]">
    <handle v-if="!isRoot"/>

    <div class="row align-items-center">
      <div class="col-auto">
        <fa-icon icon="chevron-down" size="lg" v-b-toggle="uid"></fa-icon>
      </div>

      <div v-if="Object.keys(options).length > 0 && logicBoxElements.length > 0" class="col">
        <select-box v-model="element.type">
          <template v-if="Object.keys(optionGroups).length > 0">
            <optgroup v-for="(optionKeys, label) in optionGroups" :label="label">
              <option v-for="optionKey in optionKeys" :value="optionKey">{{ options[optionKey] }}</option>
            </optgroup>
          </template>

          <option v-else v-for="(value, key) in options" :value="key">{{ value }}</option>
        </select-box>
      </div>

      <div v-if="logicBoxElements.length < 1" class="col font-italic">
        {{ emptyElementsText }}

        <div class="invalid-feedback" v-bind:class="{'is-invalid': errors.includes('elements')}">
          {{ validationFailedText }}
        </div>
      </div>

      <div class="col-auto ml-auto">
        <div class="row">
          <div v-if="!isRoot && (logicBoxElements.length > 0 || controlledElements)" class="col-auto">
            <button-delete @click="remove" title="Delete" class="pt-1 pr-0"/>
          </div>

          <div v-if="!controlledElements || logicBoxElements.length === 0" class="col-auto">
            <button-add @click="add" title="Add"/>
          </div>
        </div>
      </div>
    </div>

    <sub-card v-if="optionDescriptions.hasOwnProperty(element.type) && logicBoxElements.length > 0"
              class="max-overflow small mb-2">
      {{ optionDescriptions[element.type] }}
    </sub-card>

    <b-collapse visible :id="uid" :ref="uid" v-model="isOpen">
      <draggable v-model="element[elementsName]" :group="controlledElements ? uid : group"
                 handle=".handle" @change="onMove($event)">
        <logic-box
            v-for="(elem, elemIdx) in logicBoxElements"
            :key="elemIdx"
            :uid="uid + '_' + elemIdx"
            :element="elem"
            :elements-name="elementsName"
            :group="group"
            :validate-method-name="validateMethodName"
            :empty-elements-text="emptyElementsText"
            :validation-failed-text="validationFailedText"
            :parent-type="element.type"
            :index="elemIdx"
            :options="options"
            :option-groups="optionGroups"
            :option-descriptions="optionDescriptions"
            :should-have-elements="shouldHaveElements"
            :controlled-elements="controlledElements"
            @add="addElement($event)"
            @remove="removeElement($event)"
            @promote="promoteElement($event)"
            @demote="demoteElement($event)"
            v-slot="slotProps"
            ref="logicBoxComponents">
          <slot v-bind="slotProps"/>
        </logic-box>
      </draggable>
    </b-collapse>
  </div>

  <div v-else class="position-relative" v-bind:class="styleClass">
    <handle/>

    <slot v-bind:type="parentType" v-bind:index="index" v-bind:element="element"
          v-bind:add="() => $emit('promote', index)" v-bind:remove="() => $emit('remove', index)"/>
  </div>
</template>

<script>
    import Draggable from 'vuedraggable';
    import ValidationMixin from "../../mixins/ValidationMixin";

    export default {
        name: "LogicBox",
        components: {
            Draggable,
        },
        mixins: [ValidationMixin],
        data() {
            return {
                isOpen: true,
            };
        },
        props: {
            uid: String,
            element: Object,
            elementsName: String,
            group: String,
            validateMethodName: String,
            emptyElementsText: String,
            validationFailedText: String,
            parentType: String,
            index: {
                type: Number,
                default: 0,
            },
            options: {
                type: Object,
                default: () => ({
                    'AND': 'All conditions must be met (AND)',
                    'OR': 'At least one of the conditions must be met (OR)'
                })
            },
            optionGroups: {
                type: Object,
                default: () => ({})
            },
            optionDescriptions: {
                type: Object,
                default: () => ({})
            },
            isRoot: {
                type: Boolean,
                default: false,
            },
            shouldHaveElements: {
                type: Boolean,
                default: false,
            },
            controlledElements: {
                type: Boolean,
                default: false,
            },
        },
        computed: {
            styleClass() {
                const styleClass = [];

                if (this.isRoot)
                    styleClass.push('mt-3');

                if (this.isRoot || this.$parent.$parent.$parent.styleClass.includes('bg-primary-light'))
                    styleClass.push('bg-info-light', 'border-info');
                else
                    styleClass.push('bg-primary-light', 'border-primary');

                return styleClass;
            },

            isLogicBox() {
                return typeof this.element === 'object' &&
                    this.element.hasOwnProperty(this.elementsName);
            },

            logicBoxElements() {
                return this.element[this.elementsName];
            },
        },
        methods: {
            validateLogicBox() {
                let logicBoxValid = true;
                let elementsValid = true;
                let childrenValid = true;

                if (this.isLogicBox && this.logicBoxElements.length > 0)
                    logicBoxValid = !this.$refs.logicBoxComponents
                        .map(logicBoxComponent => logicBoxComponent.validateLogicBox())
                        .includes(false);
                else if (this.isLogicBox && this.shouldHaveElements)
                    elementsValid = this.validateField('elements', this.element.conditions.length > 0);
                else if (!this.isLogicBox && this.validateMethodName && this.$children.length > 0) {
                    if (typeof this.$children[1][this.validateMethodName] === 'function')
                        childrenValid = this.$children[1][this.validateMethodName]();
                }

                logicBoxValid = this.validateField('logicBox', logicBoxValid);
                elementsValid = this.validateField('elements', elementsValid);
                childrenValid = this.validateField('children', childrenValid);

                return logicBoxValid && elementsValid && childrenValid;
            },

            onMove(event) {
                if (event.hasOwnProperty('removed') && !this.isRoot && this.logicBoxElements.length === 1)
                    this.$emit('demote', this.index);
            },

            add() {
                this.$emit('add', this.element);
                this.isOpen = true;
            },

            remove() {
                this.$emit('remove', {group: null, index: this.index});
            },

            addElement(elem) {
                this.$emit('add', elem);
            },

            removeElement(idx) {
                if (this.controlledElements) {
                    const {group, index} = idx;
                    this.$emit('remove', {group: group || this.element, index});
                }
                else {
                    this.element[this.elementsName].splice(idx, 1);
                    if (!this.isRoot && this.element[this.elementsName].length === 1)
                        this.$emit('demote', this.index);
                }
            },

            promoteElement(index) {
                const element = this.element[this.elementsName][index];
                const elementCopy = JSON.parse(JSON.stringify(element));

                const logicBox = {
                    type: Object.keys(this.options)[0],
                    [this.elementsName]: [elementCopy],
                };

                this.$set(this.element[this.elementsName], index, logicBox);
                this.$emit('add', this.element[this.elementsName][index]);
            },

            demoteElement(index) {
                const element = this.element[this.elementsName][index][this.elementsName][0];
                const elementCopy = JSON.parse(JSON.stringify(element));

                this.$set(this.element[this.elementsName], index, elementCopy);
            },
        }
    };
</script>

// gui/react/src/LogicBox.tsx
import React from 'react';

export type LogicBox<K extends string, E> = { type: string } & { [name in K]: (LogicBox<K, E> | E)[] };

export interface LogicBoxProps<K extends string, E> {
    logicBox: LogicBox<K, E>,
    elementsName: K,
    render: (type: string, index: number, element: E, add: () => void, remove: () => void) => React.ReactElement,
    add?: () => E,
    onChange?: (oldLogicBox: LogicBox<K, E>, newLogicBox: LogicBox<K, E>) => void,
    options?: { [key: string]: string },
    optionGroups?: { [group: string]: string[] },
    optionDescriptions?: { [key: string]: string },
    exactNumberOfElements?: number,
}

export function LogicBox<K extends string, E>(
    {
        logicBox, elementsName, render, add, onChange, exactNumberOfElements,
        options = {
            'AND': 'All conditions must be met (AND)',
            'OR': 'At least one of the conditions must be met (OR)'
        },
        optionGroups = {},
        optionDescriptions = {},
    }: LogicBoxProps<K, E>
) {
    return <LogicBoxLeaf
        rootLogicBox={logicBox}
        logicBox={logicBox}
        elementsName={elementsName}
        render={render}
        add={add}
        index={-1}
        parentType={null}
        parentIndexes={[]}
        options={options}
        optionGroups={optionGroups}
        optionDescriptions={optionDescriptions}
        exactNumberOfElements={exactNumberOfElements}
        onChange={onChange}
    />;
}

interface LogicBoxLeafProps<K extends string, E> {
    rootLogicBox: LogicBox<K, E>,
    logicBox: LogicBox<K, E> | E,
    elementsName: K,
    render: (type: string, index: number, element: E, add: () => void, remove: () => void) => React.ReactElement,
    add?: () => E,
    index: number,
    parentType: string | null,
    parentIndexes: number[],
    options: { [key: string]: string },
    optionGroups: { [group: string]: string[] },
    optionDescriptions: { [key: string]: string },
    exactNumberOfElements?: number,
    onChange?: (oldLogicBox: LogicBox<K, E>, newLogicBox: LogicBox<K, E>) => void,
}

function LogicBoxLeaf<K extends string, E>(
    {
        rootLogicBox, logicBox, elementsName, render, add, index, parentType, parentIndexes,
        options, optionGroups, optionDescriptions, exactNumberOfElements, onChange
    }: LogicBoxLeafProps<K, E>
) {
    const isLogicBox = (element: LogicBox<K, E> | E): element is LogicBox<K, E> =>
        'type' in logicBox && elementsName in logicBox;

    const goToLeaf = (logicBox: LogicBox<K, E>, indexPath: number[]): LogicBox<K, E> =>
        indexPath.reduce((leaf, index) =>
            leaf[elementsName][index] as LogicBox<K, E>, logicBox);

    const changeType = (newType: string) => {
        if (onChange) {
            const logicBoxNew = JSON.parse(JSON.stringify(rootLogicBox));
            const leaf = goToLeaf(logicBoxNew, index >= 0 ? [...parentIndexes, index] : parentIndexes);
            leaf.type = newType;

            onChange(rootLogicBox, logicBoxNew);
        }
    };

    const addElement = () => {
        let elements = (logicBox as LogicBox<K, E>)[elementsName];
        if (add && onChange && (!exactNumberOfElements || elements.length < exactNumberOfElements)) {
            const logicBoxNew = JSON.parse(JSON.stringify(rootLogicBox));
            const leaf = goToLeaf(logicBoxNew, index >= 0 ? [...parentIndexes, index] : parentIndexes);

            leaf[elementsName].push(add());

            elements = (logicBoxNew as LogicBox<K, E>)[elementsName];
            while (exactNumberOfElements && elements.length < exactNumberOfElements)
                leaf[elementsName].push(add());

            onChange(rootLogicBox, logicBoxNew);
        }
    };

    const removeElement = () => {
        if (onChange && index >= 0) {
            const logicBoxNew = JSON.parse(JSON.stringify(rootLogicBox));
            const leaf = goToLeaf(logicBoxNew, parentIndexes);

            if (exactNumberOfElements) {
                const node = leaf[elementsName][index];
                if (isLogicBox(node))
                    leaf[elementsName][index] = node[elementsName][0];
            }
            else {
                leaf[elementsName].splice(index, 1);
                if (parentIndexes.length > 0 && leaf[elementsName].length === 1) {
                    const parentLeaf = goToLeaf(logicBoxNew, parentIndexes.slice(0, -1));
                    parentLeaf[elementsName][parentIndexes[0]] = leaf[elementsName][0];
                }
            }

            onChange(rootLogicBox, logicBoxNew);
        }
    };

    const createLeaf = () => {
        if (add && onChange && index >= 0) {
            const logicBoxNew = JSON.parse(JSON.stringify(rootLogicBox));
            const leaf = goToLeaf(logicBoxNew, parentIndexes);

            leaf[elementsName][index] = {
                type: Object.keys(options)[0],
                [elementsName]: [leaf[elementsName][index], add()],
            } as LogicBox<K, E>;

            onChange(rootLogicBox, logicBoxNew);
        }
    };

    if (!isLogicBox(logicBox))
        return render(parentType as string, index, logicBox, createLeaf, removeElement);

    return (
        <div className={index === -1 || parentIndexes.length % 2 === 1 ? 'logic-box first' : 'logic-box second'}>
            <div className="logic-box-header">
                {Object.keys(options).length > 0 && logicBox[elementsName].length > 0 && (
                    <select onChange={e => changeType(e.target.value)} value={logicBox.type}>
                        {Object.keys(optionGroups).length > 0
                            ? Object.keys(optionGroups).map(label =>
                                <optgroup key={label} label={label}>
                                    {optionGroups[label].map(option =>
                                        <option key={option} value={option}>{options[option]}</option>
                                    )};
                                </optgroup>
                            )
                            : Object.keys(options).map(option =>
                                <option key={option} value={option}>{options[option]}</option>
                            )
                        }
                    </select>
                )}

                {index >= 0 && logicBox[elementsName].length > 0 &&
                <button onClick={_ => removeElement()}>
                    Delete
                </button>
                }

                {(!exactNumberOfElements || logicBox[elementsName].length < exactNumberOfElements) &&
                <button onClick={_ => addElement()}>
                    Add
                </button>}
            </div>

            {logicBox[elementsName].map((elem, idx) => {
                return <LogicBoxLeaf
                    key={idx}
                    rootLogicBox={rootLogicBox}
                    logicBox={elem}
                    elementsName={elementsName}
                    render={render}
                    add={add}
                    index={idx}
                    parentType={logicBox.type}
                    parentIndexes={index >= 0 ? [...parentIndexes, index] : parentIndexes}
                    options={options}
                    optionGroups={optionGroups}
                    optionDescriptions={optionDescriptions}
                    exactNumberOfElements={exactNumberOfElements}
                    onChange={onChange}/>;
            })}
        </div>
    );
}
