// vue_app/src/components/helpers/Property.vue
<template>
  <div class="row align-items-center">
    <template v-if="resourceInfo">
      <div class="col-auto p-0">
        <div class="property-resource read-only" v-bind:class="{'btn-sm': small}">
          {{ dataset.title }}
        </div>
      </div>

      <div class="col-auto p-0">
        <div class="property-resource read-only mx-2" v-bind:class="{'btn-sm': small}">
          {{ resource.dataset.collection_id }}
        </div>
      </div>

      <div v-if="!singular && !readOnly" class="col-auto pl-0 ml-0 my-1">
        <button-add @click="$emit('clone')" size="sm" title="Add another property"/>
        <button-delete v-if="allowDelete" class="ml-2" @click="$emit('delete')" size="sm" title="Remove this property"/>
      </div>
    </template>

    <template v-for="prop in props">
      <div v-if="!Array.isArray(prop.resources) && prop.inPath" class="col-auto">
        <fa-icon icon="arrow-right"/>
      </div>

      <div v-if="prop.value[0] === '' && !readOnly" :value="prop.value[0]" class="col-auto p-0 my-1">
        <select-box @input="updateProperty($event, prop.idx)"
                    v-bind:class="{'is-invalid': errors.includes(`value_${prop.idx}`), 'form-control-sm': small}">
          <template v-if="Array.isArray(prop.resources)">
            <option v-for="collection in prop.resources" :key="collection.id" :value="collection.id">
              {{ collection.label }}
            </option>
          </template>

          <template v-else>
            <option value="" disabled selected>Choose a referenced collection</option>
            <option value="__value__">Value (do not follow reference)</option>
            <option v-for="collection in Object.keys(prop.resources).sort()" :key="collection" :value="collection">
              {{ collection }}
            </option>
          </template>
        </select-box>
      </div>

      <template v-else-if="!Array.isArray(prop.resources) && prop.inPath">
        <div v-if="readOnly" class="col-auto p-0">
          <div class="property-path read-only" v-bind:class="{'btn-sm': small}">
            {{ prop.value[0] }}
          </div>
        </div>

        <div v-else class="col-auto p-0">
          <button type="button" class="property-path" v-bind:class="{'btn-sm': small}"
                  @click="$emit('resetProperty', prop.idx)">
            {{ prop.value[0] }}
          </button>
        </div>
      </template>

      <template v-if="prop.value[0] !== '' && prop.value[0] !== '__value__'">
        <div v-if="!Array.isArray(prop.resources)" class="col-auto">
          <fa-icon icon="arrow-right"/>
        </div>

        <div v-if="!prop.value[1] && !readOnly" class="col-auto p-0 my-1">
          <select-box :value="prop.value[1]" @input="updateProperty($event, prop.idx + 1)"
                      v-bind:class="{'is-invalid': errors.includes(`value_${prop.idx}`), 'form-control-sm': small}">
            <option value="" selected disabled>Choose a property</option>
            <option v-for="propertyOpt in Object.keys(prop.properties).sort()" :value="propertyOpt">
              {{ propertyOpt }}
            </option>
          </select-box>
        </div>

        <div v-else-if="readOnly" class="col-auto p-0">
          <div class="property-path read-only" v-bind:class="{'btn-sm': small}">
            {{ prop.value[1] }}
          </div>
        </div>

        <div v-else class="col-auto p-0">
          <button type="button" class="property-path" v-bind:class="{'btn-sm': small}"
                  @click="$emit('resetProperty', prop.idx + 1)">
            {{ prop.value[1] }}
          </button>
        </div>
      </template>
    </template>
  </div>
</template>

<script>
    import ValidationMixin from "../../mixins/ValidationMixin";

    export default {
        name: "Property",
        mixins: [ValidationMixin],
        props: {
            property: Array,
            readOnly: {
                type: Boolean,
                default: false,
            },
            small: {
                type: Boolean,
                default: false,
            },
            singular: {
                type: Boolean,
                default: false,
            },
            allowDelete: {
                type: Boolean,
                default: true,
            },
            resourceInfo: {
                type: Boolean,
                default: true,
            }
        },
        computed: {
            resource() {
                return this.$root.getResourceById(this.property[0]);
            },

            dataset() {
                const datasets = this.$root.getDatasets(
                    this.resource.dataset.timbuctoo_graphql, this.resource.dataset.timbuctoo_hsid);
                return datasets[this.resource.dataset.dataset_id];
            },

            props() {
                return new Array(Math.floor(this.property.length / 2))
                    .fill(null)
                    .map((_, idx) => {
                        const propertyIdx = idx * 2;
                        return {
                            idx: propertyIdx,
                            value: this.property.slice(propertyIdx, propertyIdx + 2),
                            resources: this.getResourcesForIndex(propertyIdx),
                            properties: this.getPropertiesForIndex(propertyIdx),
                            inPath: this.readOnly || this.property[propertyIdx] !== '__value__',
                        };
                    });
            },
        },
        methods: {
            validateProperty() {
                this.errors = [];
                return !this.props.map(prop => {
                    const valid =
                        (prop.value[0] === '__value__') || (prop.value.find(value => value === '') === undefined);
                    return this.validateField(`value_${prop.idx}`, valid);
                }).includes(false);
            },

            getReferencedCollections(referencedCollections) {
                const collections = {};
                referencedCollections.forEach(collectionId =>
                    collections[collectionId] = this.dataset.collections[collectionId]);
                return collections;
            },

            getPropertiesForCollection(collectionId) {
                return this.dataset.collections.hasOwnProperty(collectionId)
                    ? this.dataset.collections[collectionId].properties : {};
            },

            getResourcesForIndex(index) {
                if (index === 0)
                    return this.$root.resources;

                const collectionId = index > 2 ? this.property[index - 2] : this.resource.dataset.collection_id;
                const property = this.getPropertiesForCollection(collectionId)[this.property[index - 1]];
                return this.getReferencedCollections(property.referencedCollections);
            },

            getPropertiesForIndex(index) {
                const collectionId = index === 0 ? this.resource.dataset.collection_id : this.property[index];
                return this.getPropertiesForCollection(collectionId);
            },

            updateProperty(newValue, index) {
                this.$set(this.property, index, newValue);

                const collectionId = this.property.length > 2
                    ? this.property.slice(-2)[0]
                    : this.resource.dataset.collection_id;

                const prop = this.property.slice(-1)[0];
                const properties = prop ? this.getPropertiesForCollection(collectionId)[prop] : null;
                if (properties && properties.referencedCollections.length > 0)
                    this.property.push('', '');
            },
        },
    };
</script>

// gui/react/src/Property.tsx
import React from 'react';
import {Collections, Dataset, Properties} from './dataset';

export interface PropertyProps {
    dataset: Dataset,
    datasetId: string,
    collectionId: string,
    property: string[],
    readOnly?: boolean,
    singular?: boolean,
    add?: () => void,
    remove?: () => void,
    entityTypeSelectionInfo?: boolean,
    onChange?: (oldProperty: string[], newProperty: string[]) => void;
}

export function Property(
    {
        dataset, datasetId, collectionId, property, add, remove, onChange,
        readOnly = false,
        singular = false,
        entityTypeSelectionInfo = true
    }: PropertyProps
) {
    const getPropertiesForIndex = (index: number): Properties | null => {
        const collId = index === 0 ? collectionId : property[index - 1];
        return getPropertiesForCollection(collId);
    };

    const getPropertiesForCollection = (collectionId: string): Properties | null => {
        return collectionId in dataset.collections ? dataset.collections[collectionId].properties : null;
    };

    const getCollectionsForIndex = (index: number | null): Collections | null => {
        if (index === null)
            return null;

        const properties = getPropertiesForIndex(index - 1);
        if (properties) {
            const prop = properties[property[index - 1]];
            return getReferencedCollections(prop.referencedCollections);
        }

        return null;
    };

    const getReferencedCollections = (referencedCollections: string[]): Collections => {
        return referencedCollections
            .filter(collectionId => collectionId in dataset.collections)
            .reduce<Collections>((acc, collectionId) => {
                acc[collectionId] = dataset.collections[collectionId];
                return acc;
            }, {});
    };

    const updateProperty = (newValue: string, index: number) => {
        if (onChange) {
            const newProperty = [...property];
            newProperty[index] = newValue;

            const length = newProperty.length;
            const collId = length > 2 ? newProperty[length - 2] : collectionId;
            const prop = newProperty[length - 1];

            if (newValue === '__value__')
                newProperty.splice(length - 1);

            const props = getPropertiesForCollection(collId);
            const properties = prop && props ? props[prop] : null;
            if (properties && properties.referencedCollections.length > 0)
                newProperty.push('', '');

            onChange(property, newProperty);
        }
    };

    const resetProperty = (index: number) => {
        if (onChange) {
            const newProperty = [...property];

            const replaceBy = (index % 2 === 1) ? ['', ''] : [''];
            newProperty.splice(index, (newProperty.length - index), ...replaceBy);

            onChange(property, newProperty);
        }
    };

    const properties = new Array(Math.floor((property.length + 1) / 2))
        .fill(null)
        .map((_, idx) => {
            const collectionIdx = idx > 0 ? (idx * 2) - 1 : null;
            const propIdx = idx * 2;

            return {
                key: `${collectionIdx}_${propIdx}`,
                collectionIdx,
                collection: collectionIdx ? property[collectionIdx] : null,
                collections: getCollectionsForIndex(collectionIdx),
                propIdx,
                property: property[propIdx],
                properties: getPropertiesForIndex(propIdx),
            };
        });

    return (
        <div className="property">
            {entityTypeSelectionInfo && <>
                <div className="property-pill resource-pill property-resource">
                    {datasetId}
                </div>

                <div className="property-pill resource-pill property-resource">
                    {collectionId}
                </div>

                {add && !singular && !readOnly &&
                <button className="property-button" title="Add another property" onClick={add}>
                    Add
                </button>}

                {remove && !singular && !readOnly &&
                <button className="property-button" title="Remove this property" onClick={remove}>
                    Remove
                </button>}
            </>
            }

            {properties.map(prop =>
                <React.Fragment key={prop.key}>
                    {prop.collections && <>
                        <div className="property-sep">→</div>

                        {prop.collection === '' && !readOnly &&
                        <button className="property-pill property-path property-select"
                                onClick={_ => console.log(prop.collections)}>
                            Select value
                        </button>
                        }

                        {prop.collection && readOnly &&
                        <div className="property-pill property-path property-entity">
                            {prop.collections[prop.collection].title || prop.collection}
                        </div>
                        }

                        {prop.collection && !readOnly &&
                        <button className="property-pill property-path property-entity"
                                onClick={_ => prop.collectionIdx != null && resetProperty(prop.collectionIdx)}>
                            {prop.collections[prop.collection].title || prop.collection}
                        </button>
                        }
                    </>}

                    {prop.properties && prop.property !== '__value__' && <>
                        {prop.collection && <div className="property-sep">→</div>}

                        {prop.property === '' && !readOnly &&
                        <button className="property-pill property-path property-select"
                                onClick={_ => console.log(prop.properties)}>
                            Select value
                        </button>
                        }

                        {prop.property && readOnly &&
                        <div className="property-pill property-path property-prop">
                            {prop.properties[prop.property].isInverse && '← '}
                            {prop.properties[prop.property].shortenedUri}
                        </div>
                        }

                        {prop.property && !readOnly &&
                        <button className="property-pill property-path property-prop"
                                onClick={_ => prop.propIdx != null && resetProperty(prop.propIdx)}>
                            {prop.properties[prop.property].isInverse && '← '}
                            {prop.properties[prop.property].shortenedUri}
                        </button>
                        }
                    </>}
                </React.Fragment>
            )}

            {!entityTypeSelectionInfo && !singular && !readOnly && (add || remove) &&
            <div className="property-buttons">
                {add && <button title="Add another property" onClick={add}>Add</button>}
                {remove && <button title="Remove this property" onClick={remove}>Remove</button>}
            </div>
            }
        </div>
    );
}
